# NB: this file was automatically generated by Dynare
#     from rbc_final_run_sim.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(8, 8);
gp = zeros(8, 16, 8);
end
return (rp, gp)
end
