# NB: this file was automatically generated by Dynare
#     from gali_forward.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(9, 14);
gp = zeros(9, 9, 14);
end
return (rp, gp)
end
