# NB: this file was automatically generated by Dynare
#     from gali_current.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(9, 14);
gp = zeros(9, 15, 14);
end
return (rp, gp)
end
