# NB: this file was automatically generated by Dynare
#     from 5.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(15, 13);
gp = zeros(15, 23, 13);
end
return (rp, gp)
end
