# NB: this file was automatically generated by Dynare
#     from 5.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(15, 13);
gp = zeros(15, 15, 13);
end
return (rp, gp)
end
