# NB: this file was automatically generated by Dynare
#     from 5.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(18, 10);
gp = zeros(18, 18, 10);
end
return (rp, gp)
end
