# NB: this file was automatically generated by Dynare
#     from rbc_final_run.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(8, 8);
gp = zeros(8, 8, 8);
end
return (rp, gp)
end
