# NB: this file was automatically generated by Dynare
#     from 4.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(8, 7);
gp = zeros(8, 16, 7);
end
return (rp, gp)
end
