# NB: this file was automatically generated by Dynare
#     from 4.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(8, 7);
gp = zeros(8, 8, 7);
end
return (rp, gp)
end
