# NB: this file was automatically generated by Dynare
#     from rbc_run.mod
#
function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[7]=0;
    ys_[6]=params[7];
    R_eff=1/(params[1]*exp((-params[8])));
    yk_ratio=params[3]/(R_eff-(1-params[2]));
    ik_ratio=exp(params[8])-(1-params[2]);
    iy_ratio=yk_ratio*ik_ratio;
    y_per_n=yk_ratio^(params[3]/(1-params[3]));
    gy_ratio=params[7]/(y_per_n*ys_[5]);
    cy_ratio=1-iy_ratio-gy_ratio;
    ys_[5]=(1-params[3])*params[5]/(1-params[3]+cy_ratio*params[4]);
    ys_[1]=y_per_n*ys_[5];
    ys_[3]=yk_ratio*ys_[1];
    ys_[4]=iy_ratio*ys_[1];
    ys_[2]=ys_[1]-ys_[4]-ys_[6];
    # Auxiliary equations
ys_[8]=1/ys_[2]*params[1]*exp((-(params[8]+exo_[1])))*(1+ys_[1]*params[3]/ys_[3]-params[2]);
end
end
