# NB: this file was automatically generated by Dynare
#     from 2.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(10, 9);
gp = zeros(10, 10, 9);
end
return (rp, gp)
end
