# NB: this file was automatically generated by Dynare
#     from 2.mod
#
function steady_state!(ys_::Vector{<: Real}, exo_::Vector{<: Real}, params::Vector{<: Real})
@inbounds begin
    ys_[6]=1;
    ys_[3]=params[6];
    ys_[9]=(1-ys_[3])/params[8];
    ys_[8]=1-ys_[3];
    k_y_ratio=params[3]/(1/params[1]-(1-params[2]));
    ys_[2]=ys_[3]*k_y_ratio^(params[3]/(1-params[3]));
    ys_[4]=k_y_ratio*ys_[2];
    ys_[5]=params[2]*ys_[4];
    ys_[1]=ys_[2]-ys_[5];
    ys_[7]=ys_[2]/ys_[3];
    term_labor_benefit=(1-params[3])*ys_[2]/ys_[3]/ys_[1];
    denom_A=params[9]+params[8]*params[1]*(1-params[9])/(1-params[1]*(1-params[8]));
    params[5]=(1-ys_[3])*term_labor_benefit/denom_A;
    ys_[10]=(1-params[9])*params[8]*params[1]*params[5]/((1-ys_[3])*(1-params[1]*(1-params[8])));
    # Auxiliary equations
end
end
